### ISSUE TITLE
農田收益計算結果的數量 錯誤

### ISSUE THREAD

**Issue by asd0210a** [bobosheep/farm-tool#2]
您好 配置=> 幼苗: 發/增/升, 鐮刀收割+6, 6級田, 加熱溫室, 有互助
收割量應是(3 +10 +2 +6) x (1+0.8+0.1) =40
但系統顯示27 (此應是種子收割量)

**Comment by bobosheep** [comment]
您好，剛剛我自己測試結果 41 唷，公式應該為 (10 + 2 + 6) * 1.8 * 1.25 = 40.5 (4捨5入為 41)。
不確定你是否有按錯，如果還是有誤的話麻煩截圖給我，謝謝你。

**Comment by asd0210a** [comment]
哈哈 結果是我裝備那邊 沒有按新增此裝備
